export { default as Header } from './Header'
export { default as Button } from './Button'
export { default as CurrentShow } from './CurrentShow'
export { default as NewsList } from './NewsList'
export { default as Partner } from './Partner'
export { default as Footer } from './Footer'